### ISSUE TITLE
Workstations do not work anymore for me

### ISSUE THREAD

**Issue by dmi3mis** [gusztavvargadr/workstations#59]
git clone https://github.com/gusztavvargadr/workstations
cd workstations\src\me
vagrant up
Bringing machine 'work' up with 'virtualbox' provider...
==> work: Box 'gusztavvargadr/w16s-vs17c' could not be found. Attempting to find and install...
    work: Box Provider: virtualbox
    work: Box Version: >= 0
==> work: Loading metadata for box 'gusztavvargadr/w16s-vs17c'
    work: URL: https://vagrantcloud.com/gusztavvargadr/w16s-vs17c
==> work: Adding box 'gusztavvargadr/w16s-vs17c' (v1803.0.0-deprecated) for provider: virtualbox
    work: Downloading: https://vagrantcloud.com/gusztavvargadr/boxes/w16s-vs17c/versions/1803.0.0-deprecated/providers/virtualbox.box
    work: Progress: 100% (Rate: 31507/s, Estimated time remaining: --:--:--)
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and that enough disk space
is available and then try again.
The output from attempting to unpackage (if any):

bsdtar.EXE: Error opening archive: Unrecognized archive format

I suggest this problem can be resolved if we change  components\vs\vagrant.yml file

from 

v17c:
  includes:
    - components/vs/core
  box: w16s-vs17c

to
v17c:
  includes:
    - components/vs/core
  box: w10e-vs17c

**Comment by gusztavvargadr** [comment]
@dmi3mis sorry for the inconvenience and thanks for the detailed log. Indeed, the box https://app.vagrantup.com/gusztavvargadr/boxes/w16s-vs17c/ has been deprecated, https://app.vagrantup.com/gusztavvargadr/boxes/w10e-vs17c/ is recommended as that's the only VS one I plan to maintain in the future.

I'll publish a fix soon for this, in the meantime, please let me know if you have any other feedback.

**Comment by kaidokert** [comment]
Seeing as https://app.vagrantup.com/gusztavvargadr/boxes/visual-studio/ seems to be the current one, should the vagrant.yml simply be updated with that ?

**Comment by gusztavvargadr** [comment]
@kaidokert indeed, cleaned up old images, but forgot to update here. Sorry for the inconvenience, will provide a patch soon.

**Comment by gusztavvargadr** [comment]
@kaidokert this has been fixed now in #66 and available on `master`, thanks for the patience 👍
