### ISSUE TITLE
Error when launching machine

### ISSUE THREAD

**Issue by simonkirkham** [gusztavvargadr/workstations#60]
I get a WinRM error then trying to spin up the machine.

PS C:\vagrant\workstations\src\people\me> vagrant up playground
Bringing machine 'playground' up with 'virtualbox' provider...
==> playground: Cloning VM...
==> playground: Matching MAC address for NAT networking...
==> playground: Checking if box 'gusztavvargadr/w10e-vs17c' is up to date...
==> playground: Setting the name of the VM: me_playground_1529864003121_56138
==> playground: Auto-generating node name for Chef...
==> playground: Fixed port collision for 3389 => 33389. Now on port 2200.
==> playground: Fixed port collision for 5985 => 55985. Now on port 2201.
==> playground: Fixed port collision for 5986 => 55986. Now on port 2202.
==> playground: Fixed port collision for 22 => 2222. Now on port 2203.
==> playground: Clearing any previously set network interfaces...
==> playground: Preparing network interfaces based on configuration...
    playground: Adapter 1: nat
==> playground: Forwarding ports...
    playground: 3389 (guest) => 2200 (host) (adapter 1)
    playground: 5985 (guest) => 2201 (host) (adapter 1)
    playground: 5986 (guest) => 2202 (host) (adapter 1)
    playground: 22 (guest) => 2203 (host) (adapter 1)
==> playground: Running 'pre-boot' VM customizations...
==> playground: Booting VM...
==> playground: Waiting for machine to boot. This may take a few minutes...
    playground: WinRM address: 127.0.0.1:2201
    playground: WinRM username: vagrant
    playground: WinRM execution_time_limit: PT2H
    playground: WinRM transport: negotiate
An error occurred executing a remote WinRM command.
Shell: Cmd
Command: hostname
Message: [WSMAN ERROR CODE: 2147942421]: <f:WSManFault Code='2147942421' Machine='127.0.0.1' xmlns:f='http://schemas.microsoft.com/wbem/wsman/1/wsmanfault'><f:Message><f:ProviderFault path='%systemroot%\system32\winrscmd.dll' provider='Shell cmd plugin'>The device is not ready. </f:ProviderFault></f:Message></f:WSManFault>

If I run "vagrant provision" after I get an the error - 
`=> playground: ================================================================================
==> playground: Error Resolving Cookbooks for Run List:
==> playground: ================================================================================
==> playground: Missing Cookbooks:
==> playground: ------------------
==> playground: No such cookbook: gusztavvargadr_workstations_core
==> playground: Expanded Run List:
`

**Comment by gusztavvargadr** [comment]
@simonkirkham what is your host OS and version and which version of VirtualBox do you use? I will try to see if I can reproduce.

**Comment by simonkirkham** [comment]
Thanks, 
My host OS is Windows 10 (version 1803) and I am running VirtualBox 5.2.12.

**Comment by gusztavvargadr** [comment]
@simonkirkham in the meantime, you can try a `vagrant reload --provision` or `vagrant halt` and `vagrant up --provision` after instead. Simple `vagrant provision` is probably failing as the `vagrant up` fails and the required shared folders for Chef might not be mapped properly.

Btw, the first boot can also fail sometimes due to the fact that the boxes are sysprepped, so they will reboot implicitly during `vagrant up`, some Vagrant race conditions might report WinRM availability earlier than expected, but this is just a guess. I'll try to reproduce and will get back to you.

**Comment by simonkirkham** [comment]
Same error  doing a reload and provision - 

PS C:\vagrant\workstations\src\people\me> vagrant reload --provision
==> work: VM not created. Moving on...
==> playground: Attempting graceful shutdown of VM...
==> playground: Checking if box 'gusztavvargadr/w10e-vs17c' is up to date...
==> playground: Clearing any previously set forwarded ports...
==> playground: Clearing any previously set network interfaces...
==> playground: Preparing network interfaces based on configuration...
    playground: Adapter 1: nat
==> playground: Forwarding ports...
    playground: 3389 (guest) => 33389 (host) (adapter 1)
    playground: 5985 (guest) => 55985 (host) (adapter 1)
    playground: 5986 (guest) => 55986 (host) (adapter 1)
    playground: 22 (guest) => 2222 (host) (adapter 1)
==> playground: Running 'pre-boot' VM customizations...
==> playground: Booting VM...
==> playground: Waiting for machine to boot. This may take a few minutes...
    playground: WinRM address: 127.0.0.1:55985
    playground: WinRM username: vagrant
    playground: WinRM execution_time_limit: PT2H
    playground: WinRM transport: negotiate
==> playground: Machine booted and ready!
==> playground: Checking for guest additions in VM...
==> playground: Mounting shared folders...
    playground: /vagrant => C:/vagrant/workstations/src/people/me
    playground: /vagrant-workstations => C:/vagrant/workstations
    playground: C:/vagrant-chef/ba1bfee0059282e71a80e2eebfd2f036/cookbooks => C:/vagrant/workstations/src/people/me
==> playground: Running provisioner: chef_solo...
==> playground: Generating chef JSON and uploading...
==> playground: Running chef-solo...
==> playground: [2018-06-28T07:30:21+00:00] INFO: Started chef-zero at chefzero://localhost:1 with repository at C:/vagrant-chef/ba1bfee0059282e71a80e2eebfd2f036
==> playground:   One version per cookbook
==> playground: [2018-06-28T07:30:21+00:00] INFO: Started chef-zero at chefzero://localhost:1 with repository at C:/vagrant-chef/ba1bfee0059282e71a80e2eebfd2f036
==> playground:   One version per cookbook
==> playground: Starting Chef Client, version 13.8.5
==> playground: [2018-06-28T07:30:21+00:00] INFO: *** Chef 13.8.5 ***
==> playground: [2018-06-28T07:30:21+00:00] INFO: *** Chef 13.8.5 ***
==> playground: [2018-06-28T07:30:21+00:00] INFO: Platform: x64-mingw32
==> playground: [2018-06-28T07:30:21+00:00] INFO: Platform: x64-mingw32
==> playground: [2018-06-28T07:30:21+00:00] INFO: Chef-client pid: 4372
==> playground: [2018-06-28T07:30:21+00:00] INFO: Chef-client pid: 4372
==> playground: [2018-06-28T07:30:21+00:00] INFO: The plugin path C:\chef\ohai\plugins does not exist. Skipping...
==> playground: [2018-06-28T07:30:21+00:00] INFO: The plugin path C:\chef\ohai\plugins does not exist. Skipping...
==> playground: [2018-06-28T07:30:24+00:00] INFO: Setting the run_list to ["recipe[gusztavvargadr_workstations_core::requirements]", "recipe[gusztavvargadr_workstations_os::requirements]", "recipe[gusztavvargadr_workstations_nuget::requirements]", "recipe[gusztavvargadr_workstations_vagrant::requirements]", "recipe[gusztavvargadr_workstations_dockere::requirements]", "recipe[gusztavvargadr_workstations_aws::requirements]", "recipe[gusztavvargadr_workstations_git::requirements]", "recipe[gusztavvargadr_workstations_svn::requirements]"] from CLI options
==> playground: [2018-06-28T07:30:24+00:00] INFO: Setting the run_list to ["recipe[gusztavvargadr_workstations_core::requirements]", "recipe[gusztavvargadr_workstations_os::requirements]", "recipe[gusztavvargadr_workstations_nuget::requirements]", "recipe[gusztavvargadr_workstations_vagrant::requirements]", "recipe[gusztavvargadr_workstations_dockere::requirements]", "recipe[gusztavvargadr_workstations_aws::requirements]", "recipe[gusztavvargadr_workstations_git::requirements]", "recipe[gusztavvargadr_workstations_svn::requirements]"] from CLI options
==> playground: [2018-06-28T07:30:24+00:00] INFO: Run List is [recipe[gusztavvargadr_workstations_core::requirements], recipe[gusztavvargadr_workstations_os::requirements], recipe[gusztavvargadr_workstations_nuget::requirements], recipe[gusztavvargadr_workstations_vagrant::requirements], recipe[gusztavvargadr_workstations_dockere::requirements], recipe[gusztavvargadr_workstations_aws::requirements], recipe[gusztavvargadr_workstations_git::requirements], recipe[gusztavvargadr_workstations_svn::requirements]]
==> playground: [2018-06-28T07:30:24+00:00] INFO: Run List is [recipe[gusztavvargadr_workstations_core::requirements], recipe[gusztavvargadr_workstations_os::requirements], recipe[gusztavvargadr_workstations_nuget::requirements], recipe[gusztavvargadr_workstations_vagrant::requirements], recipe[gusztavvargadr_workstations_dockere::requirements], recipe[gusztavvargadr_workstations_aws::requirements], recipe[gusztavvargadr_workstations_git::requirements], recipe[gusztavvargadr_workstations_svn::requirements]]
==> playground: [2018-06-28T07:30:24+00:00] INFO: Run List expands to [gusztavvargadr_workstations_core::requirements, gusztavvargadr_workstations_os::requirements, gusztavvargadr_workstations_nuget::requirements, gusztavvargadr_workstations_vagrant::requirements, gusztavvargadr_workstations_dockere::requirements, gusztavvargadr_workstations_aws::requirements, gusztavvargadr_workstations_git::requirements, gusztavvargadr_workstations_svn::requirements]
==> playground: [2018-06-28T07:30:24+00:00] INFO: Run List expands to [gusztavvargadr_workstations_core::requirements, gusztavvargadr_workstations_os::requirements, gusztavvargadr_workstations_nuget::requirements, gusztavvargadr_workstations_vagrant::requirements, gusztavvargadr_workstations_dockere::requirements, gusztavvargadr_workstations_aws::requirements, gusztavvargadr_workstations_git::requirements, gusztavvargadr_workstations_svn::requirements]
==> playground: [2018-06-28T07:30:24+00:00] INFO: Starting Chef Run for vagrant-0551e8cd
==> playground: [2018-06-28T07:30:24+00:00] INFO: Starting Chef Run for vagrant-0551e8cd
==> playground: [2018-06-28T07:30:24+00:00] INFO: Running start handlers
==> playground: [2018-06-28T07:30:24+00:00] INFO: Running start handlers
==> playground: [2018-06-28T07:30:24+00:00] INFO: Start handlers complete.
==> playground: [2018-06-28T07:30:24+00:00] INFO: Start handlers complete.
==> playground: resolving cookbooks for run list: ["gusztavvargadr_workstations_core::requirements", "gusztavvargadr_workstations_os::requirements", "gusztavvargadr_workstations_nuget::requirements", "gusztavvargadr_workstations_vagrant::requirements", "gusztavvargadr_workstations_dockere::requirements", "gusztavvargadr_workstations_aws::requirements", "gusztavvargadr_workstations_git::requirements", "gusztavvargadr_workstations_svn::requirements"]
==> playground: ================================================================================
==> playground: Error Resolving Cookbooks for Run List:
==> playground: ================================================================================
==> playground: Missing Cookbooks:
==> playground: ------------------
==> playground: No such cookbook: gusztavvargadr_workstations_core
==> playground: Expanded Run List:
==> playground: ------------------
==> playground: * gusztavvargadr_workstations_core::requirements
==> playground: * gusztavvargadr_workstations_os::requirements
==> playground: * gusztavvargadr_workstations_nuget::requirements
==> playground: * gusztavvargadr_workstations_vagrant::requirements
==> playground: * gusztavvargadr_workstations_dockere::requirements
==> playground: * gusztavvargadr_workstations_aws::requirements
==> playground: * gusztavvargadr_workstations_git::requirements
==> playground: * gusztavvargadr_workstations_svn::requirements
==> playground: System Info:
==> playground: ------------
==> playground: chef_version=13.8.5
==> playground: platform=windows
==> playground: platform_version=10.0.16299
==> playground: ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x64-mingw32]
==> playground: program_name=C:/opscode/chef/bin/chef-solo
==> playground: executable=C:/opscode/chef/bin/chef-solo
==> playground: Running handlers:
==> playground: [2018-06-28T07:30:24+00:00] ERROR: Running exception handlers
==> playground: [2018-06-28T07:30:24+00:00] ERROR: Running exception handlers
==> playground: Running handlers complete
==> playground: [2018-06-28T07:30:24+00:00] ERROR: Exception handlers complete
==> playground: [2018-06-28T07:30:24+00:00] ERROR: Exception handlers complete
==> playground: Chef Client failed. 0 resources updated in 03 seconds
==> playground: [2018-06-28T07:30:24+00:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
==> playground: [2018-06-28T07:30:24+00:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
==> playground: [2018-06-28T07:30:24+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> playground: [2018-06-28T07:30:24+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> playground: [2018-06-28T07:30:24+00:00] FATAL: Net::HTTPServerException: 412 "Precondition Failed"
==> playground: [2018-06-28T07:30:24+00:00] FATAL: Net::HTTPServerException: 412 "Precondition Failed"
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by gusztavvargadr** [comment]
@simonkirkham can you please double check you have all the tools installed mentioned at https://github.com/gusztavvargadr/workstations#installing-the-tools? It seems you have at least `vagrant-berkshelf` missing, the `vagrant up` log should contain entries about vendoring cookbooks and it's not the case.

**Comment by simonkirkham** [comment]
It was indeed a missing corrupt berkshelf installation. It had been previously installed and working so not sure what happened. 

Thanks for the assistance.
