### ISSUE TITLE
Error running provision for docker

### ISSUE THREAD

**Issue by simonkirkham** [gusztavvargadr/workstations#61]
I had to change the config to use the w10e-vs17c box as w16s-vs17c has been deprecated. 

`v17c:
  includes:
    - components/vs/core
  box: w10e-vs17c`

I am then getting this error when provisioning the machine

==> playground:   * powershell_script[Install 'docker' package] action run
==> playground:     [execute] The term 'Get-WindowsFeature' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
==> playground:     ================================================================================
==> playground:     Error executing action `run` on resource 'powershell_script[Install 'docker' package]'
==> playground:     ================================================================================
==> playground:     Mixlib::ShellOut::ShellCommandFailed
==> playground:     ------------------------------------
==> playground:     Expected process to exit with [0], but received '1'
==> playground:     ---- Begin output of "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20180630-4336-fx8tz2.ps1" ----
==> playground:     STDOUT:
==> playground:     STDERR: The term 'Get-WindowsFeature' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
==> playground:     ---- End output of "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20180630-4336-fx8tz2.ps1" ----
==> playground:     Ran "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20180630-4336-fx8tz2.ps1" returned 1
==> playground:     Resource Declaration:
==> playground:     ---------------------
==> playground:     # In C:/chef/cache/cookbooks/gusztavvargadr_workstations_dockere/recipes/tools.rb
==> playground:       1: powershell_script 'Install \'docker\' package' do
==> playground:       2:   code <<-EOH
==> playground:       3:     Install-Package -Name docker -ProviderName DockerMsftProvider -Force
==> playground:       4:   EOH
==> playground:       5:   action :run
==> playground:       6:   guard_interpreter :powershell_script
==> playground:       7:   not_if '(Get-Package -Name docker -ProviderName DockerMsftProvider) -ne $null'
==> playground:       8: end
==> playground:     Compiled Resource:
==> playground:     ------------------
==> playground:     # Declared in C:/chef/cache/cookbooks/gusztavvargadr_workstations_dockere/recipes/tools.rb:1:in `from_file'
==> playground:     powershell_script("Install 'docker' package") do
==> playground:       action [:run]
==> playground:       guard_interpreter :powershell_script
==> playground:       default_guard_interpreter :powershell_script
==> playground:       command nil
==> playground:       backup 5
==> playground:       returns 0
==> playground:       user nil
==> playground:       interpreter "powershell.exe"
==> playground:       declared_type :powershell_script
==> playground:       cookbook_name "gusztavvargadr_workstations_dockere"
==> playground:       recipe_name "tools"
==> playground:       code "    Install-Package -Name docker -ProviderName DockerMsftProvider -Force\n"
==> playground:       domain nil
==> playground:       not_if "(Get-Package -Name docker -ProviderName DockerMsftProvider) -ne $null"
==> playground:     end
==> playground:     System Info:
==> playground:     ------------
==> playground:     chef_version=13.8.5
==> playground:     platform=windows
==> playground:     platform_version=10.0.16299
==> playground:     ruby=ruby 2.4.3p205 (2017-12-14 revision 61247) [x64-mingw32]
==> playground:     program_name=C:/opscode/chef/bin/chef-solo
==> playground:     executable=C:/opscode/chef/bin/chef-solo
==> playground: [2018-06-30T08:47:54+00:00] INFO: Running queued delayed notifications before re-raising exception
==> playground: [2018-06-30T08:47:54+00:00] INFO: Running queued delayed notifications before re-raising exception
==> playground: Running handlers:
==> playground: [2018-06-30T08:47:54+00:00] ERROR: Running exception handlers
==> playground: [2018-06-30T08:47:54+00:00] ERROR: Running exception handlers
==> playground: Running handlers complete
==> playground: [2018-06-30T08:47:54+00:00] ERROR: Exception handlers complete
==> playground: [2018-06-30T08:47:54+00:00] ERROR: Exception handlers complete
==> playground: Chef Client failed. 11 resources updated in 32 seconds
==> playground: [2018-06-30T08:47:54+00:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
==> playground: [2018-06-30T08:47:54+00:00] FATAL: Stacktrace dumped to C:/chef/cache/chef-stacktrace.out
==> playground: [2018-06-30T08:47:54+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> playground: [2018-06-30T08:47:54+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> playground: [2018-06-30T08:47:54+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: powershell_script[Install 'docker' package] (gusztavvargadr_workstations_dockere::tools line 1) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> playground: ---- Begin output of "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20180630-4336-fx8tz2.ps1" ----
==> playground: STDOUT:
==> playground: STDERR: The term 'Get-WindowsFeature' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
==> playground: ---- End output of "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20180630-4336-fx8tz2.ps1" ----
==> playground: Ran "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20180630-4336-fx8tz2.ps1" returned 1
==> playground: [2018-06-30T08:47:54+00:00] FATAL: Mixlib::ShellOut::ShellCommandFailed: powershell_script[Install 'docker' package] (gusztavvargadr_workstations_dockere::tools line 1) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> playground: ---- Begin output of "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20180630-4336-fx8tz2.ps1" ----
==> playground: STDOUT:
==> playground: STDERR: The term 'Get-WindowsFeature' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
==> playground: ---- End output of "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20180630-4336-fx8tz2.ps1" ----
==> playground: Ran "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe" -NoLogo -NonInteractive -NoProfile -ExecutionPolicy Bypass -InputFormat None -File "C:/Users/vagrant/AppData/Local/Temp/chef-script20180630-4336-fx8tz2.ps1" returned 1
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

Tried removing the docker stack - 
`    - stacks/infrastructure/dockere` 
from the box but still get same issue.

**Comment by gusztavvargadr** [comment]
@simonkirkham I've added some temporary changes in the branch of #63 so that it uses the correct box and disables Docker for now. You can try to recreate the machine, the Chef attributes / run lists might get cached on the guest. Let me know how that works out.

Please note that Docker will not work with VirtualBox and Windows 10 as it does not support nested virtualization, but it will work with HyperV.

**Comment by simonkirkham** [comment]
That PR does indeed work. Thanks very much.
