### ISSUE TITLE
Upgrade to latest version of components

### ISSUE THREAD

**Issue by gusztavvargadr** [gusztavvargadr/workstations#62]
- [ ] Vagrant helpers
- [ ] Chef cookbooks
- [ ] Vagrant boxes

Related to #59.
Related to #60.
Related to #61.

**Comment by simonkirkham** [comment]
Worked but I needed to switch the chocolatey package for fiddler as fiddler4 is not available. 
See here - https://github.com/simonkirkham/workstations/commit/54f449eb115c3f73d6387b64a75bf52f55cfd92f

**Comment by gusztavvargadr** [comment]
@simonkirkham thanks for pointing it out, fiddler4 was removed earlier indeed, I see it was added back recently, will integrate that as well.
